version: '3'
services:
#  web:
#    build: .
#    container_name: 'data-beetle-main-container'
#    ports:
#     - 7090:7090
#    links:
#      - 'data-beetle-redis-container'
#      - 'data-beetle-elasticsearch-container'
#      - 'data-beetle-postgis-container'
#    volumes:
#      - ../../volumes/main:/opt
  redis:
    image: "redis:alpine"
    container_name: 'data-beetle-redis-container'
    volumes:
      - ../../../volumes/redis:/data
    ports:
      - 6379:6379
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.1.2"
    container_name: 'data-beetle-elasticsearch-container'
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    volumes:
      - ../../../volumes/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  postgis:
      image: "mdillon/postgis"
      container_name: 'data-beetle-postgis-container'
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=n0m3l0s3
        - POSTGRES_USER=root
      volumes:
        - ../../../volumes/postgis:/var/lib/postgresql/data